### ISSUE TITLE
Include .trim() in cli-color directly.

### ISSUE THREAD

**Issue by rentalhost** [medikoo/cli-color#18]
Currently we need require the `cli-color/trim` to support trim. And it is a little redundant, for me. Why I'll require a feature (`trim`) inside a major feature (`cli-color`)? It's like I need to include `cli-color/width` to get the console width, because `cli-color` is focused in color.

**Currently:**

    var cli = require("cli-color"),
        trim = require("cli-color/trim");
    
    console.log(trim(cli.blue("hello")));

**Suggestion:**

    var cli = require("cli-color");
    
    console.log(cli.trim(cli.blue("hello")));

**Version:**

 * `0.4.x` Implements this feature;
 * `1.0.x` Remove support to `cli-color/trim` way;

**Comment by medikoo** [comment]
It may make sense, as indeed it's not large utility. I'll schedule it for v1.

**Comment by medikoo** [comment]
Addressed and published with v1.0.0. Still `trim` was also renamed to `strip`
