### ISSUE TITLE
Using cli-color as in a module

### ISSUE THREAD

**Issue by NetForces** [medikoo/cli-color#26]
Here is a very simple example:

File node_functions.js:

```
var clc = require('/usr/lib/node_modules/cli-color');

module.exports = {
  pass: function () {
    console.log(clc.bgGreen.white.bold("PASS"))
  },
  fail: function () {
    console.log(clc.bgRed.white.bold("FAIL"))
  }
};
```

File test.js:

```
var tools = require('node_functions.js');
console.log(tools.fail());
```

The expected result would be simply the word FAIL in bold white over red backgroud.

However the result is:

![conferences ssh 2015-06-29 14-07-38](https://cloud.githubusercontent.com/assets/984831/8414758/38cdd75a-1e68-11e5-9daa-e019c69cc9b8.png)

I have no idea where the "undefined" comes from.

Running cli-color@1.0.0 with node v0.10.39

**Comment by medikoo** [comment]
It comes from `console.log(tools.fail())`, it logs result of `tools.fail()` call which returns undefined.

**Comment by NetForces** [comment]
Doh !

Changed the module for:

```
var clc = require('/usr/lib/node_modules/cli-color');

module.exports = {
  pass: function () {
    return(clc.bgGreen.white.bold("PASS"));
  },
  fail: function () {
    return(clc.bgRed.white.bold("FAIL"));
  }
};
```

Works great. Thanks.
