### ISSUE TITLE
Camo dropped your images; your readme is torched

### ISSUE THREAD

**Issue by StoneCypher** [medikoo/cli-color#41]
It's torched on npm too

**Comment by medikoo** [comment]
Thanks @StoneCypher for reporting. Looking into that

**Comment by medikoo** [comment]
Fixed now. Great thanks for reporting

**Comment by StoneCypher** [comment]
Semi-confirmed.

Don't know if you care, but the second table of colors on NPM shows as narrow strips rather than squares.

**Comment by medikoo** [comment]
Thanks, I see it as:

<img width="901" alt="Screenshot 2022-06-05 at 11 51 29" src="https://user-images.githubusercontent.com/122434/172044914-b854b9ea-fb6b-466f-b2b1-5fe76ee3226b.png">

What browser are you using?

**Comment by StoneCypher** [comment]
Ah.  It's about width.

I discovered it because at my initial zoom, they were "normal" looking in Firefox, but zero-width and therefore invisible in Edge.  Then I decided to take screenshots.  After the firefox screenshot, and I went back to Edge, I decided to take them with the inspector out, so that you could see metrics.  Then I had to go back to Firefox, and on opening the inspector, I saw it go from `looks fine` to `what the hell`

[You can see it happen here](https://www.youtube.com/watch?v=y5oVglM1xtY)

To stop this, observe that GitHub has a minimum width, and remove probably two columns, so that the color chips will still be at full width once the column is at minimum width.

The effect in the video has been successfully replicated on evergreen-current Chrome, Edge, and Firefox, all on Win10 pro x64

**Comment by medikoo** [comment]
@StoneCypher great thanks for explaining in detail.

Indeed it doesn't look good in narrow window

As I check, I would either need to restructure the table so it has fewer items in a row (max 5 I assume) or insert an image instead.

I'll leave it open for now

**Comment by StoneCypher** [comment]
yeah i think 5 is prolly max

note: `what the hell` is actually a technical term

**Comment by medikoo** [comment]
I've actually updated it, so it's presented via image. 

If you have a better idea let me know, but I consider it as addressed at this point.

Great thanks for reporting it!

**Comment by medikoo** [comment]
Thanks for ping. It was just published (CI is already configured, I just needed to bump version in `package.json`).
