### ISSUE TITLE
cli-color can't print object

### ISSUE THREAD

**Issue by danilobatistaqueiroz** [medikoo/cli-color#45]
cli-color can't print object, for example:  

```js
const clc = require("cli-color")
const x = {id:1,name:'abc'}
console.log(clc.red(x))
```
The output is:  
[object Object]

**Comment by medikoo** [comment]
@danilobatistaqueiroz this is by design. `clc` methods expect text input. If you want rich object coloring you should rather rely on native Node.js methods. Or if you want to have just object representation turned red, then you can achieve it via:

```javascript
const util = reqquire('util');
...
console.log(clc.red(util.inspect(x)));
```
